---
- hosts: atahualpa
  vars:
    nodejs_version: "0.10."
    nodejs_install_method : "package"
    zeromq_version: "4.0.5"

    logstash_forwarder_files:
      - paths:
          - /var/log/atahualpa.log
        fields:
          type: atahualpa

    logstash_forwarder_logstash_server: "elk"
    logstash_forwarder_logstash_server_ip: "{{ hostvars['elk1']['ansible_ssh_host'] }}"
    logstash_forwarder_logstash_server_port: 5000

  roles: 
    - { role : bastly.nodejs, sudo: yes }
    - { role : bastly.zeromq, sudo: yes }
    - { role : bastly.nodezeromq, sudo: yes }
    - { role : bastly.pythondev, sudo: yes }
    - { role : bastly.openssl-gather, sudo: yes }
    - { role : bastly.logstash-forwarder, sudo: yes }
    - { role : bastly.git-publisher, repo_to_install: "git@github.com:Bastly/atahualpa.git", repo_branch: "develop", app_installation_dir : "/vagrant/atahualpa"}
    - { role : bastly.upstart, sudo: yes, extra_options: "--curaca {{ hostvars['curaca1']['ansible_eth0']['ipv4']['address'] }} --consul {{ hostvars['consul1']['ansible_eth0']['ipv4']['address'] }} --redis {{ hostvars['redis1']['ansible_eth0']['ipv4']['address'] }}",  script_path : "/vagrant/atahualpa", service: "atahualpa"}
    - { role : bastly.git-publisher, repo_to_install: "git@github.com:Bastly/connector-rest.git", repo_branch: "HEAD", app_installation_dir : "/vagrant/connector-rest"}
    - { role : bastly.upstart, sudo: yes, extra_options: "--atahualpa {{ hostvars['atahualpa1']['ansible_ssh_host'] }} --orion {{ hostvars['orion1']['ansible_ssh_host'] }}:1026 --callback {{ hostvars['atahualpa1']['ansible_ssh_host'] }}:8080",  script_path : "/vagrant/connector-rest", service: "connector-rest"}
