---
- hosts: atahualpa
  vars:
    nodejs_version: "0.12."
    nodejs_install_method : "package"
    zeromq_version: "4.0.5"
    repo_to_install: "git@github.com:Bastly/atahualpa.git"
    app_installation_dir : "/vagrant/atahualpa"
    connect_to : "{{ hostvars['chaski1']['ansible_ssh_host'] }}"
    logstash_forwarder_files:
      - paths:
          - /var/log/atahualpa.log
        fields:
          type: atahualpa

    logstash_forwarder_logstash_server: "elk"
    logstash_forwarder_logstash_server_ip: "{{ hostvars['elk1']['ansible_ssh_host'] }}"
    logstash_forwarder_logstash_server_port: 5000



  roles: 
    - { role : bastly.nodejs, sudo: yes }
    - { role : bastly.zeromq, sudo: yes }
    - { role : bastly.nodezeromq, sudo: yes }
    - { role : bastly.pythondev, sudo: yes }
    - { role : bastly.git-publisher }
    - { role : bastly.openssl-gather, sudo: yes }
    - { role : bastly.logstash-forwarder, sudo: yes }
    - { role : bastly.start-nodeapp, sudo: yes }
