---
- hosts: chaski
  vars:
    nodejs_version: "0.10."
    nodejs_install_method : "package"
    zeromq_version: "4.0.5"
    repo_to_install: "git@github.com:Bastly/chaski.git"
    app_installation_dir : "/home/vagrant/client"
    connect_to : "{{ hostvars['atahualpa1']['ansible_ssh_host'] }}"

  roles: 
    - { role : bastly.nodejs, sudo: yes }
    - { role : bastly.zeromq, sudo: yes }
    - { role : bastly.nodezeromq, sudo: yes }
    - { role : bastly.pythondev, sudo: yes }
    - { role : bastly.git-publisher }
    - { role : bastly.start-nodeapp, sudo: yes }
