---

- hosts: consulClient
  sudo: true
  pre_tasks:
    - name: add dns
      sudo: yes
      command: echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null

    - name: update apt
      sudo: yes
      apt: update_cache=yes

  roles:
    - { role : bastly.consul, sudo: yes }
  vars:
    consul_version: 0.5.0
    consul_install_dnsmasq: false
    consul_is_ui: false
    consul_is_server: false
    consul_bootstrap: false
    consul_datacenter: "BastlyInfra"
    consul_node_name: "{{inventory_hostname}}"
    consul_servers: ["{{ hostvars['consul1']['ansible_eth1']['ipv4']['address'] }}"]
    consul_bind_address: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
    consul_advertise_address: "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"
    consul_join_at_start: true
    # configure service
    consul_log_level: "INFO"
    consul_rejoin_after_leave: "true"
    consul_leave_on_terminate: "false"
