---
# installs redis and configures it
- hosts: ddbb
  sudo: true

  pre_tasks:
    - name: user panel dependencies
      apt: pkg={{ item }}
      sudo: true
      with_items:
        - mongodb-server

  tasks:
    - apt: update_cache=yes

    - name: install make
      apt: pkg={{ item }}
      sudo: true
      with_items:
        - make
        - build-essential
        - awscli
        - git

    - name: Creates directory
      file: path=/vagrant/redis state=directory

    - name: download redis 3.0
      get_url: url=http://download.redis.io/releases/redis-3.0.1.tar.gz dest=/vagrant/redis mode=0440

    - name: extract tar
      unarchive: src=/vagrant/redis/redis-3.0.1.tar.gz dest=/vagrant/redis copy=no

    - name: Install redisServer
      command: make
      args:
        chdir: /vagrant/redis/redis-3.0.1

    - name: Install redisServer
      command: make install
      args:
        chdir: /vagrant/redis/redis-3.0.1

    - name: Install redis and spawn server
      shell: echo -n | sudo utils/install_server.sh
      args:
        chdir: /vagrant/redis/redis-3.0.1

    # create a directory if it doesn't exist
    - file: path=/scripts state=directory mode=0774

    # create a directory if it doesn't exist
    - file: path=/backup state=directory mode=0774

    # Copy db save script
    - copy: src=./scripts/perform_copy.sh dest=/scripts/perform_copy.sh owner=root group=root mode=0644

    # Adds cron for redis backup
    - cron: name="redisBackup" minute="0" hour="5" job="redis-cli bgsave"

    # Adds cron for redis backup
    - cron: name="store backup redis" minute="30" hour="5" job="/scripts/perform_copy.sh"

    # Copy mongo config
    - template: src=./configFiles/mongodb.conf.j2 dest=/etc/mongodb.conf owner=root group=root mode=0644

    # Restart mongo with new interface
    - service: name=mongodb state=restarted

    # tasks file for roles/bastly.git-publisher
    - name: clone secret keys if not already cloned
      git: repo=git@bitbucket.org:bastly/secret-keys.git dest=~/secret-keys accept_hostkey=True version=master

    - name: copy amazon keys to aws config
      command: cp ~/secret-keys/s3BackupCredentials ~/.aws/credentials

    # copy amazon dest file
    - copy: src=./configFiles/amazonZone.config dest=~/.aws/config owner=root group=root mode=0644