---
#
- hosts: dev
  sudo: true

  roles: 
    - { role : bastly.npm-global-deps, sudo: yes }

  tasks:
    - name: importing vars
      include_vars: vagrantConfig.yml

    - name: install git
      apt: pkg={{ item }}
      sudo: true
      with_items:
        - git

    - name: config git email 
      sudo: true
      #TODO change vagrant for user when mergin openstack
      sudo_user: vagrant
      command: git config --global user.email {{ git.userEmail }}

    - name: config git name 
      sudo: true
      #TODO change vagrant for user when mergin openstack
      sudo_user: vagrant
      command: git config --global user.name {{ git.name }}
