---
- hosts: log_gather
  vars:
    logstash_forwarder_logstash_server: "elk"
    logstash_forwarder_logstash_server_ip: "{{ hostvars['elk1']['ansible_eth1']['ipv4']['address'] }}"
    logstash_forwarder_logstash_server_port: 5000


  tasks:
    - debug: msg="ip of elk is {{ logstash_forwarder_logstash_server_ip }}"
    
  roles:
    - { role : bastly.openssl_gather, sudo: yes }
    - { role : bastly.logstash-forwarder, sudo: yes }
