---
- hosts: all
  vars:
    nodejs_version: "0.10.35*"
    nodejs_install_method : "package"
    zeromq_version: "4.0.5"

  roles: 
    - { role : bastly.nodejs, sudo: yes }
    - { role : bastly.zeromq, sudo: yes }
    - { role : bastly.nodezeromq, sudo: yes }
    - { role : bastly.pythondev, sudo: yes }
    - { role : bastly.git-publisher}