---
- hosts: all
  sudo: true
  vars:
    nodejs_version: "0.10.35*"
    nodejs_install_method : "package"
    zeromq_version: "4.0.5"

  roles: 
    - { role : bastly.nodejs }
    - { role : bastly.zeromq }
    - { role : bastly.nodezeromq }
    - { role : bastly.pythondev }
    - { role : bastly.git-publisher}