---
# file: site.yml
- include: ssh_check.yml
- include: log_gather.yml
- include: consulServer.yml
- include: consulClient.yml
- include: elk.yml
- include: chaski.yml
- include: atahualpa.yml
- include: webdev.yml
- include: vim.yml
- include: dev.yml
- include: npm-publisher.yml
