---
# file: site.yml
- include: ssh_check.yml
- include: sshSudo.yml
- include: consulServer.yml
- include: consulClient.yml
- include: node.yml
- include: zeromq.yml
- include: atahualpa.yml
#- include: log_gather.yml
- include: elk.yml
- include: chaski.yml
- include: orion.yml
- include: connectorRest.yml
- include: jenkins.yml
- include: redis.yml
- include: curaca.yml
