---
- hosts: webdev
  vars:
    nodejs_version: "0.10."
    nodejs_install_method : "package"

#    - { role : bastly.git-publisher, repo_to_install: "git@github.com:Bastly/sdk-js-browser.git", app_installation_dir : "/vagrant/sdk-js"}
   
  tasks:
    - name: importing vars
      include_vars: vagrantConfig.yml

    - name: config git email 
      shell: git config --global user.email {{ git.userEmail }} 

    - name: config git name 
      shell: git config --global user.name {{ git.name }}
