---
# tasks file for roles/bastly.git-publisher
- name: ensure helloworld repo is available
  git: repo=https://github.com/Bastly/node-hello.git dest=/home/vagrant/client accept_hostkey=True

- name: install app npm dependencies.
  npm: path=/home/vagrant/client