---
# tasks file for roles/bastly.nodejs

- name: show status vars
  debug: msg="installing through {{ nodejs_install_method }} with version {{ nodejs_version }}"

- include: package.yml
  when: nodejs_install_method == "package"

- name: node.js | Check if the node versions is already installed
  command: node --version
  ignore_errors: yes
  register: node_version
  changed_when: node_version.rc != 0 or node_version.stdout != "v{{ nodejs_version }}"
  when: nodejs_install_method == "source"

- include: source.yml
  when: nodejs_install_method == "source" and node_version.changed