---
# tasks file for roles/bastly.nodejs

- name: show status vars
  debug: msg="installing through {{ nodejs_install_method }} with version {{ nodejs_version }}"

- name: node.js | Check if the node versions is already installed
  command: node --version
  ignore_errors: yes
  register: node_version

- name: show current version.
  debug: msg="current version {{ node_version.stdout }} and true {{ node_version.stdout }} != "v{{ nodejs_version }}""
  when: node_version.failed is defined and node_version.failed == false

- include: package.yml
  when: (nodejs_install_method == "package" and node_version.failed is defined) or (nodejs_install_method == "package" and node_version.stdout != "v{{ nodejs_version }}")

- include: source.yml
  when: nodejs_install_method == "source" and node_version.changed