# file: tasks/build/main.yml

- name: Build | Make sure essential build/dev tools for python are installed 
  apt: pkg={{ item }}
  with_items:
    - python-dev

- name: Check if pip is already installed.
  stat: path=/usr/local/bin/pip 
  register: pip_installed

- name: Download pip
  command: wget https://bootstrap.pypa.io/get-pip.py chdir=/tmp 
  when: pip_installed.stat.exists == false

- name: Insstall pip
  command: python get-pip.py chdir=/tmp 
  when: pip_installed.stat.exists == false
